### ISSUE TITLE
Adaugat content pe pagina contact.html

### ISSUE THREAD

**Issue by vladmihociu** [vladmihociu/twproject#2]
@Lupu-Andrei ->

   Aici punem datele noastre de contact: email ( al meu este vlad.maciu@gmail.com , dar scrie-l si pe cel de la facultate) , numele nostru, grupa, anul, profesorul indrumator. Eventual poti face si un email al proiectului de genul guessthevip.project@[a-Z]*.[a-Z]*
   @alexcoman, ar mai trebui ceva adaugat pe pagina de contact?

**Comment by alexcoman** [comment]
Salut @Lupu-Andrei și @vladmihociu,

Dacă considerați că este util, puteți să adăugați un formular de contact prin care utilizatorii să poată lua legătura cu voi. Eventual puteți să clasificați mesajele după tipul acestora (întrebări frecvente, raportarea unei probleme etc).

De asemenea ar fi util dacă pentru acest issue ați adăuga o serie de etichete (care să reflecte mai bine la ce se referă), cine este responsabil de rezolvarea acestuia etc. 

Spor la proiect!

/Alex
